### ISSUE TITLE
Confused re: BumpLabel usage

### ISSUE THREAD

**Issue by mwpowellhtx** [BalassaMarton/MSBump#18]
Compelling project you have here. You've found, as have I, that much of the battle is maintaining sanity in the package delivery pipeline, both externally as well as, especially, internally.

I'm confused, however, re: ``BumpLabel``, with or without ``LabelDigits``. How do you specify where to incorporate that label in the overall version number? i.e. for ``BumpRevision``? Or should I simply be specifying ``BumpRevision``?

Once that is specified, what do I signal to the project re: the base ``Version`` number? i.e. ``Major.Minor.Patch``, with ``Revision`` (the number I'd like to encode and/or serialize) being left unspecified?

**Comment by BalassaMarton** [comment]
@mwpowellhtx  the label is appended at the end of the version string. For example, if `BumpLabel = 'dev'` and `LabelDigits = 2` then bumping version `1.0.0` will get you to `1.0.0-dev01`, then `1.0.0-dev02` etc. It is useful when you're working on a solution that has a `PackageReference` on a package in another solution. Let's say `SolutionA.ProjectA` references on `SolutionB.ProjectB`. You want to make sure that whenever you modify and rebuild `ProjectB`, you can use the updated version in `ProjectA`. But since major, minor, patch and revision has meaning in a semantic versioning context, and you can even add prerelease labels, you're sometimes left with a CI label like 'dev'.

**Comment by mwpowellhtx** [comment]
@BalassaMarton I guess what I'm after is a way to influence ``AssemblyVersion`` bumping automatically during the build and/or packaging procedure. So, if I specify AssemblyVersion="1.0.0", then I'd like to see that incremented "1.0.0.1", "1.0.0.2", ..., "1.0.0.n", and so on.

I like the idea of labeling the package revision, though, "dev", etc. But I gather that is a separate concern from the actually ``AssemblyVersion``?

Does this connect in any way with the ``$version$`` attribute?

[See also](19), I'm not positive that tooling migration path stands in the way of this being fully realized, but I could be mistaken re: that assessment on my part.

**Comment by mwpowellhtx** [comment]
@BalassaMarton It's working pretty well. Here's what I've ended up doing making use of it. I wonder your insights.

It's not perfect shifting gears between *Debug* and *Release*, or other, *Configurations*, but it's 95% effective, I think. It would be interesting if somehow a ``Version`` tag in the respective configuration ``PropertyGroup`` tags could originate somehow from the primary Version tag, but like I said, 95.9999% effective, I think.

Other than that, I couldn't get the ``JSON`` to work for whatever reason, but I was able to get the ``csproj`` based settings to work.

I'll go ahead and close this as I think it's working for all intents and purposes.

Thoughts?
