### ISSUE TITLE
Support typical debug and release build bumping

### ISSUE THREAD

**Issue by jaredthirsk** [BalassaMarton/MSBump#2]
How can this work for both debug and release builds?  As it is now, if I switch between with the bumplabel for debug and no bumplabel for release, my release builds still have the -dev0001 suffix and I 
don't want that.

I'm not sure if there's a good way to do this or if you want to, but what I imagine is this:

At the start of a release build: (is it possible to do this before a build?)
 
1. Strip the -dev0001 suffix
2. Bump the revision number if the -dev0001 suffix was missing.  Otherwise don't bump it.

At the start of a debug build:

1. If the -dev0001 suffix was missing: bump revision and add -dev0001
2. If -dev0001 is present: increment to -dev0002 and don't bump revision.

This is perhaps a more opinionated and less open-ended approach but I would think this would facilitate the typical developer cycle better:
 - Automatically ensure every release build gets its own revision number
 - When working on new features, debug builds should be a higher version number than the previous release build.

Thoughts?  Also, have you considered supporting bumping of VerisionPrefix?
Personally, I'm thinking I'd just like to just set VersionPrefix once, and then have your bumper tool force the Version to match the VersionPrefix.  So if I update VersionPrefix to 1.0.3, the bumper before the build will set Version to 1.0.3.0, or 1.0.3.0-dev0001.

(I'm new to publishing DLLs so I'm trying to figure out some good conventions and automation.)

```
  <PropertyGroup>
    <VersionPrefix>1.0.2</VersionPrefix>
    <Version>1.0.2.11-dev0001</Version>
  </PropertyGroup>

<PropertyGroup Condition=" '$(Configuration)'=='Release'">
    <BumpRevision>True</BumpRevision>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)'=='Debug'">
    <BumpLabel>dev</BumpLabel>
    <BumpLabelDigits>4</BumpLabelDigits>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>
```

**Comment by BalassaMarton** [comment]
@jaredthirsk good idea, how about adding `BumpResetLabel`, `BumpResetPatch`, etc. properties to control this? We'll still need the conditional block, but we'll have full control over bumping or resetting any part of the version.
About supporting `VersionPrefix` and `VersionSuffix` - if I do this, I'd definitely have to rewrite the whole tool to use some sort of MSBuild project file API so that conditional blocks are properly handled (AFAIK the only usage of `VersionPrefix` and `VersionSuffix` is when you put one in a conditional block. Also, I'd have to parse both of them to determine which part of the version is in which tag, combine the two, bump it, and then split it again. I'm not sure if this can be even done with any existing API. For projects that eventually become NuGet packages, IMHO the most straight-forward versioning method is to use a single `Version` element so that your project, assembly and NuGet package versions are identical, and bump the appropriate part on build.

**Comment by BalassaMarton** [comment]
The more I use it, the more obvious it gets - we have to forget the MSBuild task approach. Say I'm working on the package, I'm in Debug configuration, then I decide that the new version is ready to deploy. I switch to Release config, hit Build and expect that the package version is modified according to the build configuration. But by the time the MSBump task runs, MSBuild has already loaded the project, and it will pass the information (including the last version from the debug build) in it to every other task, including build and pack. I'll look into the possibility of a VS extension, although I hoped that I can come up with a cross-platform solution (now that MSBuild supports .NET Core tasks as well).

**Comment by BalassaMarton** [comment]
The new version is now available on NuGet and as a standalone release.

**Comment by BalassaMarton** [comment]
The new version is now available on NuGet and as a standalone release.
