### ISSUE TITLE
SemVer suffix for prereleases

### ISSUE THREAD

**Issue by dasjestyr** [BalassaMarton/MSBump#4]
So I'm most interested in this for managing NuGet package versions. One of the things I want to be able to do is suffix `-alpha` or `-beta` to the version so that NuGet treats them as pre-release. I'm not even sure if this is supported in the csproj package info let alone MSBump. Thoughts?

**Comment by BalassaMarton** [comment]
I've tried it on a .NET Standard Class Library project, and it worked, I just had to set the `Version` property in the project file to "1.2.3-pre". MSBump still bumps the correct part on build. Does this option work for you?
I' thinking about supporting the various version elements like `PackageVersion` and `VersionSuffix` however I'm not sure what to do with them, what precedence they should have, etc. I couldn't find any documentation for this. What I know is that NuGet uses `PackageVersion`, which has a fallback to `Version`.

**Comment by dasjestyr** [comment]
It does work if I put it in by hand. I was thinking something I could work into the build configuration. For example, if it's Debug, it always suffixes `-beta` which I think would only be achievable in a way similar to your examples like:

``` xml
<PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <VersionSuffix>-beta</VersionSuffix>
 </PropertyGroup>
```

And then have that update the `Version`. Maybe it would be more consistent to have `<VersionSuffix>` suffix the Version and something like `<PackageVersionSuffix`> suffix the PackageVersion to allow specificity.

**Comment by BalassaMarton** [comment]
I see what you mean. MSBump will not parse the project file like MSBuild would, that's for sure, so even if it cared for `VersionPrefix` and `VersionSuffix` it can't decide which element to read and write. What are you doing with these nugets when they are built using the Debug configuration? If you're pushing them to a local NuGet feed so that dependent projects can update their package list (this is what I do), then use MSBump to add a `dev` label that is incremented on every build. Labelling Debug versions with `beta` is not a good idea IMHO, because it mixes up two totally different classifications.

**Comment by dasjestyr** [comment]
Oh that's actually perfect. Thanks!
